insert into field_address (street, country, state, city, zip) values ('9389 Hermina Avenue', 'United States', 'New York', 'Rochester', '14614');
insert into field_address (street, country, state, city, zip) values ('21 Mcbride Street', 'United States', 'California', 'Mountain View', '94042');
insert into field_address (street, country, state, city, zip) values ('65048 Pleasure Lane', 'United States', 'Nebraska', 'Lincoln', '68517');
insert into field_address (street, country, state, city, zip) values ('83 Eastwood Parkway', 'United States', 'Massachusetts', 'Springfield', '01129');
insert into field_address (street, country, state, city, zip) values ('6 Mendota Junction', 'United States', 'Arkansas', 'Little Rock', '72209');
insert into field_address (street, country, state, city, zip) values ('2 Huxley Court', 'United States', 'Maryland', 'Hagerstown', '21747');
insert into field_address (street, country, state, city, zip) values ('1356 Loftsgordon Pass', 'United States', 'California', 'Van Nuys', '91406');
insert into field_address (street, country, state, city, zip) values ('13682 Rutledge Plaza', 'United States', 'Pennsylvania', 'Scranton', '18505');
insert into field_address (street, country, state, city, zip) values ('54 Tony Trail', 'United States', 'Colorado', 'Greeley', '80638');
insert into field_address (street, country, state, city, zip) values ('8 Fairfield Court', 'United States', 'California', 'Glendale', '91210');
insert into field_address (street, country, state, city, zip) values ('3 Warrior Street', 'United States', 'New York', 'New York City', '10105');
insert into field_address (street, country, state, city, zip) values ('19128 Meadow Ridge Place', 'United States', 'Texas', 'Fort Worth', '76192');
insert into field_address (street, country, state, city, zip) values ('41774 Northridge Lane', 'United States', 'Texas', 'Round Rock', '78682');
insert into field_address (street, country, state, city, zip) values ('8083 Cherokee Point', 'United States', 'Oregon', 'Portland', '97229');
insert into field_address (street, country, state, city, zip) values ('2 Bartillon Drive', 'United States', 'California', 'San Francisco', '94121');
insert into field_address (street, country, state, city, zip) values ('0 Prentice Court', 'United States', 'Washington', 'Seattle', '98148');
insert into field_address (street, country, state, city, zip) values ('009 Mallard Street', 'United States', 'Mississippi', 'Jackson', '39282');
insert into field_address (street, country, state, city, zip) values ('26 Hallows Point', 'United States', 'Florida', 'Lakeland', '33811');
insert into field_address (street, country, state, city, zip) values ('9395 Gateway Trail', 'United States', 'Pennsylvania', 'Philadelphia', '19120');
insert into field_address (street, country, state, city, zip) values ('9561 Blue Bill Park Drive', 'United States', 'District of Columbia', 'Washington', '20530');
